# Generated by Django 5.2.7 on 2025-11-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='locations',
            field=models.ManyToManyField(related_name='plants', to='main_app.location'),
        ),
    ]
