# Generated by Django 5.2.7 on 2025-11-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_plant_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='locations',
            field=models.ManyToManyField(to='main_app.location'),
        ),
    ]
